name: Deploy to Lolipop

on:
  push:
    branches:
      - master   # ← デフォルトブランチに合わせる

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: deployphp/action-deploy-ftp@v1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .
          remote-dir: /
