name: Deploy to Lolipop via WebDAV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build   # out/ が生成される

      # 必要なディレクトリを事前に作成
      - name: Create necessary directories
        run: |
          # assetsディレクトリ
          curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -X MKCOL \
               "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/assets" || true

          # assets/imagesディレクトリ
          curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
               -X MKCOL \
               "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/assets/images" || true

      - name: Deploy via WebDAV with curl
        run: |
          find ./out -type f | while read file; do
            remote_path="${file#./out/}"
            dir_path=$(dirname "$remote_path")

            # ディレクトリ構造を作成
            if [ "$dir_path" != "." ]; then
              IFS='/' read -ra PARTS <<< "$dir_path"
              current_path=""
              for part in "${PARTS[@]}"; do
                if [ -n "$current_path" ]; then
                  current_path="$current_path/$part"
                else
                  current_path="$part"
                fi
                curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                     -X MKCOL \
                     "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/$current_path" 2>/dev/null || true
              done
            fi

            echo "Uploading $file to $remote_path"
            curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                 -T "$file" \
                 "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/$remote_path"
          done

          # .htaccess を明示的にアップロード
          if [ -f ".htaccess" ]; then
            echo "Uploading .htaccess"
            curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                 -T ".htaccess" \
                 "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/.htaccess"
          fi
