name: Deploy to Lolipop via WebDAV

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 必要ならビルド
      # - run: npm install && npm run build

      - name: Deploy via WebDAV with curl
        run: |
          shopt -s dotglob  # ← ドットファイルも find に含める
          for file in $(find ./out -type f -o -name ".htaccess"); do
            remote_path="${file#./out/}"
            echo "Uploading $file to $remote_path"
            curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
                 --create-dirs \
                 -T "$file" \
                 "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/$remote_path"
          done
