name: Deploy to Lolipop via WebDAV

on:
  push:
    branches:
      - master   # ブランチ名に合わせる

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ビルドが必要ならここで
      # - run: npm install && npm run build

      - name: Deploy via WebDAV
        uses: buu700/webdav-upload@v1.3.0
        with:
          url: https://staba-mahounogakuen.webdav-lolipop.jp/vivian/   # 公開フォルダ
          username: ${{ secrets.WEBDAV_USER }}
          password: ${{ secrets.WEBDAV_PASS }}
          directory: ./out
