- name: Deploy via WebDAV with curl
  run: |
    find ./out -type f | while read file; do
      remote_path="${file#./out/}"
      echo "Uploading $file to $remote_path"
      curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
           --create-dirs \
           -T "$file" \
           "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/$remote_path"
    done

    # .htaccess を明示的にアップロード
    if [ -f ".htaccess" ]; then
      echo "Uploading .htaccess"
      curl -sS -u "${{ secrets.WEBDAV_USER }}:${{ secrets.WEBDAV_PASS }}" \
           -T ".htaccess" \
           "https://staba-mahounogakuen.webdav-lolipop.jp/vivian/.htaccess"
    fi
