name: Deploy to Lolipop via WebDAV

on:
  push:
    branches:
      - master   # ← ブランチ名に合わせる

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ビルドが必要ならここで実行
      # - run: npm install && npm run build

      - name: Deploy via WebDAV
        uses: shogo82148/actions-http-upload@v1
        with:
          url: https://staba-mahounogakuen.webdav-lolipop.jp/vivian/  # 公開フォルダ vivian を指定
          username: ${{ secrets.WEBDAV_USER }}
          password: ${{ secrets.WEBDAV_PASS }}
          local-dir: ./out/
