name: Deploy to Lolipop

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ビルド（必要な場合）
      # - run: npm install && npm run build

      - name: Deploy via FTP
        uses: sand4rt/ftp-deployer@v1.5
        with:
          sftp: false
          host: ftp.lolipop.jp
          port: 21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_folder: vivian        # ← ルート直下の vivian にデプロイ
          local_folder: ./out          # ← ビルド成果物が入ってるフォルダ
          include: '["*","**/*"]'
          exclude: '[]'
          passive: true
