name: Deploy to Lolipop

on:
  push:
    branches:
      - master   # デフォルトブランチが master の場合

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Lolipop
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.lolipop.jp
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: mahounogakuen/vivian/   # 公開フォルダ (独自ドメイン設定で指定済み)
          local-dir: ./out/                   # Vite のビルド成果物
